# !/usr/bin/env python3

#!/usr/bin/env python3

# Main.py file generated by New Project wizard

# Created:   Mon Feb 10 2025
# Processor: RPI4
# Compiler:  Python 3 (Proteus)

# Modules
from goto import *
import time
import var
import pio
import resource

# Peripheral Configuration Code (do not edit)
#---CONFIG_BEGIN---
import cpu
import FileStore
import VFP
import RPi.GPIO as GPIO
import time

# Define the GPIO pins connected to the relays
relay1 = 6   # Motor 1 Forward
relay2 = 13   # Motor 1 Reverse
relay3 = 19  # Motor 2 Forward
relay4 = 26  # Motor 2 Reverse

delay_time = 2  # 2 seconds delay between direction changes

# Set up the GPIO mode
GPIO.setmode(GPIO.BCM)  # Use Broadcom pin numbering
GPIO.setup(relay1, GPIO.OUT)
GPIO.setup(relay2, GPIO.OUT)
GPIO.setup(relay3, GPIO.OUT)
GPIO.setup(relay4, GPIO.OUT)

# Initialize relays to OFF state
GPIO.output(relay1, GPIO.LOW)
GPIO.output(relay2, GPIO.LOW)
GPIO.output(relay3, GPIO.LOW)
GPIO.output(relay4, GPIO.LOW)

def main():
    try:
        while True:
            # Rotate both motors clockwise (CW)
            GPIO.output(relay1, GPIO.HIGH)  # Motor 1 Forward
            GPIO.output(relay2, GPIO.LOW)   # Motor 1 Reverse OFF
            GPIO.output(relay3, GPIO.HIGH)  # Motor 2 Forward
            GPIO.output(relay4, GPIO.LOW)   # Motor 2 Reverse OFF
            time.sleep(delay_time)

            # Stop both motors briefly
            GPIO.output(relay1, GPIO.LOW)
            GPIO.output(relay2, GPIO.LOW)
            GPIO.output(relay3, GPIO.LOW)
            GPIO.output(relay4, GPIO.LOW)
            time.sleep(0.5)

            # Rotate both motors counterclockwise (CCW)
            GPIO.output(relay1, GPIO.LOW)   # Motor 1 Forward OFF
            GPIO.output(relay2, GPIO.HIGH)  # Motor 1 Reverse
            GPIO.output(relay3, GPIO.LOW)   # Motor 2 Forward OFF
            GPIO.output(relay4, GPIO.HIGH)  # Motor 2 Reverse
            time.sleep(delay_time)

            # Stop both motors briefly
            GPIO.output(relay1, GPIO.LOW)
            GPIO.output(relay2, GPIO.LOW)
            GPIO.output(relay3, GPIO.LOW)
            GPIO.output(relay4, GPIO.LOW)
            time.sleep(0.5)
    
    except KeyboardInterrupt:
        GPIO.cleanup()  # Reset GPIO settings

if __name__ == "__main__":

    main()
